const fs=require("fs"),path=require("path");
const F=path.join(__dirname,"..","marketing","social","carousel-decks.json");
const d=JSON.parse(fs.readFileSync(F,"utf8"));
const T={
 c1:{de:[`Deine "natürliche" Creme ist der Grund, warum deine Haut noch brennt.`,`Natürlich heißt nicht sanft. Viele Naturcremes stecken voller Parfüm und ätherischer Öle.`,`Bei empfindlicher Haut ist Parfüm einer der häufigsten Auslöser.`,`Elira hält Parfüm bewusst niedrig und zertifiziert die ganze Formel.`,`COSMOS Natural zertifiziert, vegan, hergestellt in der EU.`,`Ruhigere Haut beginnt mit weniger. Entdecke die Sensitiv-Reihe. Speichere das.`],
     nl:[`Je "natuurlijke" crème is waarom je huid nog steeds brandt.`,`Natuurlijk betekent niet zacht. Veel natuurcrèmes zitten vol parfum en etherische oliën.`,`Bij de gevoelige huid is parfum een van de meest voorkomende triggers.`,`Elira houdt parfum bewust laag en certificeert de hele formule.`,`COSMOS Natural gecertificeerd, vegan, gemaakt in de EU.`,`Een rustigere huid begint met minder. Ontdek de sensitive-reeks. Bewaar dit.`]},
 c2:{de:[`8 Produkte. Halb leer. Haut trotzdem gereizt.`,`Mehr Schritte sind nicht mehr Pflege. Bei empfindlicher Haut oft mehr Reizung.`,`Du brauchst keine Sieben-Schritte-Routine. Du brauchst zwei, die zu dir passen.`,`Ein sanfter Reiniger. Eine parfümbewusste Pflege. Das ist alles.`,`COSMOS Natural zertifiziert, hergestellt in der EU.`,`Räum das Regal. Behalte zwei. Entdecke das Set. Speichere das.`],
     nl:[`8 producten. Half leeg. Huid nog steeds geïrriteerd.`,`Meer stappen is niet meer verzorging. Bij de gevoelige huid vaak meer irritatie.`,`Je hebt geen zevenstappenroutine nodig. Je hebt twee stappen nodig die bij je passen.`,`Een zachte reiniger. Een parfumbewuste crème. Dat is alles.`,`COSMOS Natural gecertificeerd, gemaakt in de EU.`,`Ruim de plank op. Houd er twee. Bekijk het set. Bewaar dit.`]},
 c3:{de:[`Retinol brachte Ergebnisse und Rötungen. Du darfst nur eins behalten.`,`Retinol glättet, aber empfindliche Haut brennt, schält und rötet sich oft.`,`Bidens Pilosa ist eine pflanzliche Retinol-Alternative.`,`Sie schenkt den glatteren, verfeinerten Look von Retinol, ohne die Reizung.`,`2% Bidens Pilosa, COSMOS zertifiziert, für jeden Hauttyp.`,`Das Gute, ohne das Brennen. Entdecke das Serum. Speichere das.`],
     nl:[`Retinol gaf resultaat én roodheid. Je mag er maar één houden.`,`Retinol maakt glad, maar de gevoelige huid brandt, schilfert en wordt vaak rood.`,`Bidens Pilosa is een plantaardig retinol-alternatief.`,`Het geeft de gladdere, verfijnde look van retinol, zonder de irritatie.`,`2% Bidens Pilosa, COSMOS gecertificeerd, voor elk huidtype.`,`Het goede, zonder het branden. Bekijk het serum. Bewaar dit.`]},
 c4:{de:[`Warum diese 65-Euro-"Clean"-Creme es nicht wert ist.`,`Zertifizierte Naturpflege muss keine sechzig Euro und mehr kosten.`,`Zahlen solltest du für die Zertifizierung, nicht für die Verpackung.`,`Elira ist COSMOS zertifiziert, vegan und parfümbewusst. Zu einem fairen Preis.`,`Echtes Siegel, kurze Zutatenliste, hergestellt in der EU.`,`Zahl für Beweise, nicht für Aufschlag. Entdecke die Reihe. Speichere das.`],
     nl:[`Waarom die "clean" crème van €65 het niet waard is.`,`Gecertificeerde natuurlijke verzorging hoeft geen zestig euro of meer te kosten.`,`Je betaalt beter voor de certificering, niet voor de verpakking.`,`Elira is COSMOS gecertificeerd, vegan en parfumbewust. Tegen een eerlijke prijs.`,`Echt keurmerk, korte ingrediëntenlijst, gemaakt in de EU.`,`Betaal voor bewijs, niet voor opslag. Bekijk de reeks. Bewaar dit.`]},
 c5:{de:[`"Natürlich" auf dem Etikett heißt nichts. Hier ist das Wort, das zählt.`,`Jede Marke darf "natürlich" draufdrucken. Niemand prüft es.`,`COSMOS ist eine unabhängige Zertifizierung. Geprüft, nicht nur behauptet.`,`Sie bestimmt, was rein darf und was draußen bleibt.`,`Elira ist COSMOS Natural zertifiziert, vegan, hergestellt in der EU.`,`Achte auf das Siegel, nicht den Slogan. Entdecke Zertifiziertes. Speichere das.`],
     nl:[`"Natuurlijk" op een etiket zegt niets. Dit is het woord dat wél telt.`,`Elk merk mag "natuurlijk" drukken. Niemand controleert het.`,`COSMOS is een onafhankelijk keurmerk. Gecontroleerd, niet alleen beweerd.`,`Het bepaalt wat erin mag, en wat eruit blijft.`,`Elira is COSMOS Natural gecertificeerd, vegan, gemaakt in de EU.`,`Let op het keurmerk, niet de slogan. Bekijk gecertificeerd. Bewaar dit.`]},
 c6:{de:[`Dieses quietschsaubere Gefühl? Du schädigst deine Haut.`,`Wenn die Haut nach dem Reinigen spannt, wurde sie ausgetrocknet.`,`Ein guter Reiniger entfernt den Tag, nicht deine Schutzbarriere.`,`Sanft, parfümbewusst und zertifizierte Naturkosmetik.`,`COSMOS Natural zertifiziert, hergestellt in der EU.`,`Sauber, nie ausgetrocknet. Entdecke den Reiniger. Speichere das.`],
     nl:[`Dat piepschone gevoel? Je beschadigt je huid.`,`Als je huid na het reinigen trekt, is hij uitgedroogd.`,`Een goede reiniger verwijdert de dag, niet je huidbarrière.`,`Zacht, parfumbewust en gecertificeerd natuurlijk.`,`COSMOS Natural gecertificeerd, gemaakt in de EU.`,`Schoon, nooit uitgedroogd. Bekijk de reiniger. Bewaar dit.`]},
 c7:{de:[`Deine juckende Kopfhaut ist keine Schuppen. Es ist dein Shampoo.`,`Scharfe Tenside und Parfüm können empfindliche Kopfhaut spannen und jucken lassen.`,`Wechsle zu beruhigender, dermatologisch getesteter Pflege für empfindliche Kopfhaut.`,`Sanft zur Kopfhaut, für jeden Haartyp geeignet.`,`Dermatologisch getestet, COSMOS Natural zertifiziert.`,`Ruhiger ab der Wurzel. Entdecke das Shampoo. Speichere das.`],
     nl:[`Je jeukende hoofdhuid is geen roos. Het is je shampoo.`,`Agressieve detergenten en parfum kunnen een gevoelige hoofdhuid laten trekken en jeuken.`,`Stap over op kalmerende, dermatologisch geteste verzorging voor een gevoelige hoofdhuid.`,`Zacht voor de hoofdhuid, geschikt voor elk haartype.`,`Dermatologisch getest, COSMOS Natural gecertificeerd.`,`Rustiger vanaf de wortel. Bekijk de shampoo. Bewaar dit.`]},
 c8:{de:[`Dreh deine Creme um. Zähl die Füllstoffe.`,`Parfüm, Füllstoffe und eine lange Liste, um die deine Haut nie gebeten hat.`,`Eine kürzere Liste heißt weniger Gründe zu reagieren.`,`Elira hält sie kurz, parfümbewusst und zertifiziert.`,`COSMOS Natural zertifiziert, vegan, hergestellt in der EU.`,`Lies das Etikett. Dann unseres. Jetzt entdecken. Speichere das.`],
     nl:[`Draai je crème om. Tel de vulstoffen.`,`Parfum, vulstoffen en een lange lijst waar je huid nooit om vroeg.`,`Een kortere lijst betekent minder redenen om te reageren.`,`Elira houdt het kort, parfumbewust en gecertificeerd.`,`COSMOS Natural gecertificeerd, vegan, gemaakt in de EU.`,`Lees het etiket. Lees dan dat van ons. Bekijk nu. Bewaar dit.`]},
 c9:{de:[`Empfindliche Haut? Hör auf, "sensitive" Produkte zu kaufen.`,`"Sensitiv" auf dem Drogerie-Etikett ist kein Standard. Es ist ein Werbewort.`,`Deine Haut braucht eine kurze, zertifizierte, parfümbewusste Formel.`,`Gemacht für Haut, die auf fast alles reagiert.`,`COSMOS Natural zertifiziert, hergestellt in der EU.`,`Tausch das Wort gegen das Siegel. Entdecke die Reihe. Speichere das.`],
     nl:[`Gevoelige huid? Stop met "sensitive" producten kopen.`,`"Sensitive" op een drogisterij-etiket is geen standaard. Het is een marketingwoord.`,`Wat je huid nodig heeft is een korte, gecertificeerde, parfumbewuste formule.`,`Gemaakt voor een huid die op bijna alles reageert.`,`COSMOS Natural gecertificeerd, gemaakt in de EU.`,`Ruil het woord voor het keurmerk. Bekijk de reeks. Bewaar dit.`]},
 c10:{de:[`3 Hautpflege-"Regeln", die empfindliche Haut leise ruinieren.`,`1. "Mehr Schritte, bessere Haut." Falsch. Mehr Schritte, mehr Auslöser.`,`2. "Es muss kribbeln." Kribbeln ist meist Reizung, kein Ergebnis.`,`3. "Natürlich ist automatisch sanft." Parfüm und Öle sagen etwas anderes.`,`Die Lösung: weniger Schritte, parfümbewusst, COSMOS zertifiziert.`,`Speichere das für deinen nächsten Kauf. Jetzt entdecken.`],
      nl:[`3 huidverzorgings-"regels" die de gevoelige huid stilletjes slopen.`,`1. "Meer stappen is een betere huid." Fout. Meer stappen, meer triggers.`,`2. "Het moet tintelen." Tintelen is meestal irritatie, geen resultaat.`,`3. "Natuurlijk is automatisch zacht." Parfum en oliën zeggen iets anders.`,`De oplossing: minder stappen, parfumbewust, COSMOS gecertificeerd.`,`Bewaar dit voor je volgende aankoop. Bekijk nu.`]},
};
for(const deck of d.decks){const t=T[deck.id];if(t){deck.slides.de=t.de;deck.slides.nl=t.nl;}}
fs.writeFileSync(F,JSON.stringify(d,null,2));
console.log("localized de+nl for",Object.keys(T).length,"decks");
